"""add_tables колонка 

Revision ID: 2d66927f1267
Revises: 794f097827dd
Create Date: 2025-09-01 00:18:48.078938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d66927f1267'
down_revision: Union[str, None] = '794f097827dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False, comment='Product name'))

    # ### end Alembic commands ###
