"""Add spot and product foreign keys

Revision ID: 794f097827dd
Revises: a87a28ce7edd
Create Date: 2025-09-01 00:08:23.967288

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '794f097827dd'
down_revision: Union[str, None] = 'a87a28ce7edd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product', sa.BigInteger(), nullable=True, comment='Link to Poster product catalog'))
        batch_op.drop_constraint('fk_transaction_products_poster_product_products', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_transaction_products_product_products'), 'products', ['product'], ['poster_product_id'])
        batch_op.drop_column('poster_product')

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('spot', sa.BigInteger(), nullable=True, comment='Link to Poster spot'))
        batch_op.create_foreign_key(batch_op.f('fk_transactions_spot_spots'), 'spots', ['spot'], ['spot_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_transactions_spot_spots'), type_='foreignkey')
        batch_op.drop_column('spot')

    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poster_product', sa.BIGINT(), autoincrement=False, nullable=True, comment='Link to Poster product catalog'))
        batch_op.drop_constraint(batch_op.f('fk_transaction_products_product_products'), type_='foreignkey')
        batch_op.create_foreign_key('fk_transaction_products_poster_product_products', 'products', ['poster_product'], ['poster_product_id'])
        batch_op.drop_column('product')

    # ### end Alembic commands ###
