"""add_tables транзакции

Revision ID: a87a28ce7edd
Revises: 1b6e2de6d9e4
Create Date: 2025-08-31 23:36:42.640931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a87a28ce7edd'
down_revision: Union[str, None] = '1b6e2de6d9e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               type_=sa.Text(),
               existing_comment='Poster user ID who created transaction',
               existing_nullable=True)
        batch_op.drop_index('ix_transactions_client_phone')
        batch_op.drop_column('is_synced_to_telegram')
        batch_op.drop_column('spot_name')
        batch_op.drop_column('table_name')
        batch_op.drop_column('client_name')
        batch_op.drop_column('client_email')
        batch_op.drop_column('client_phone')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('client_phone', sa.VARCHAR(length=20), autoincrement=False, nullable=True, comment='Client phone number'))
        batch_op.add_column(sa.Column('client_email', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Client email'))
        batch_op.add_column(sa.Column('client_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Client name'))
        batch_op.add_column(sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=True, comment='Table name'))
        batch_op.add_column(sa.Column('spot_name', sa.VARCHAR(length=255), autoincrement=False, nullable=True, comment='Spot name'))
        batch_op.add_column(sa.Column('is_synced_to_telegram', sa.BOOLEAN(), autoincrement=False, nullable=False, comment='Synced to Telegram bot'))
        batch_op.create_index('ix_transactions_client_phone', ['client_phone'], unique=False)
        batch_op.alter_column('user_id',
               existing_type=sa.Text(),
               type_=sa.INTEGER(),
               existing_comment='Poster user ID who created transaction',
               existing_nullable=True)

    # ### end Alembic commands ###
