"""add_tables колонка оплати 

Revision ID: dabd0e73dc34
Revises: 2d66927f1267
Create Date: 2025-09-01 01:00:33.160448

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dabd0e73dc34'
down_revision: Union[str, None] = '2d66927f1267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('discount', sa.Numeric(precision=10, scale=2), nullable=True, comment='Product discount'))
        batch_op.add_column(sa.Column('bonus', sa.Numeric(precision=10, scale=2), nullable=True, comment='Product bonus'))
        batch_op.add_column(sa.Column('print', sa.Integer(), nullable=True, comment='Print status: 0-no print, 1-print'))
        batch_op.add_column(sa.Column('tax_sum', sa.Numeric(precision=10, scale=2), nullable=True, comment='Total tax amount'))
        batch_op.add_column(sa.Column('weight_flag', sa.Integer(), nullable=True, comment='Weight product flag'))
        batch_op.add_column(sa.Column('barcode', sa.String(length=255), nullable=True, comment='Product barcode (if differs from catalog)'))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('payed_sum', sa.Numeric(precision=10, scale=2), nullable=True, comment='Total payment amount'))
        batch_op.add_column(sa.Column('payed_cash', sa.Numeric(precision=10, scale=2), nullable=True, comment='Cash payment amount'))
        batch_op.add_column(sa.Column('payed_card', sa.Numeric(precision=10, scale=2), nullable=True, comment='Card payment amount'))
        batch_op.add_column(sa.Column('payed_cert', sa.Numeric(precision=10, scale=2), nullable=True, comment='Certificate payment amount'))
        batch_op.add_column(sa.Column('payed_bonus', sa.Numeric(precision=10, scale=2), nullable=True, comment='Bonus payment amount'))
        batch_op.add_column(sa.Column('payed_third_party', sa.Numeric(precision=10, scale=2), nullable=True, comment='Third party payment amount'))
        batch_op.add_column(sa.Column('round_sum', sa.Numeric(precision=10, scale=2), nullable=True, comment='Rounding amount'))
        batch_op.add_column(sa.Column('pay_type', sa.Integer(), nullable=True, comment='Payment type: 0-no payment, 1-cash, 2-card, 3-mixed'))
        batch_op.add_column(sa.Column('reason', sa.Integer(), nullable=True, comment='Reason for closing without payment'))
        batch_op.add_column(sa.Column('tip_sum', sa.Numeric(precision=10, scale=2), nullable=True, comment='Service tip amount'))
        batch_op.add_column(sa.Column('print_fiscal', sa.Integer(), nullable=True, comment='Fiscal print flag: 0-no, 1-yes, 2-return'))
        batch_op.alter_column('discount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Discount percentage',
               existing_comment='Discount amount',
               existing_nullable=False)
        batch_op.alter_column('bonus',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Bonus percentage',
               existing_comment='Bonus amount',
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('bonus',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Bonus amount',
               existing_comment='Bonus percentage',
               existing_nullable=False)
        batch_op.alter_column('discount',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               comment='Discount amount',
               existing_comment='Discount percentage',
               existing_nullable=False)
        batch_op.drop_column('print_fiscal')
        batch_op.drop_column('tip_sum')
        batch_op.drop_column('reason')
        batch_op.drop_column('pay_type')
        batch_op.drop_column('round_sum')
        batch_op.drop_column('payed_third_party')
        batch_op.drop_column('payed_bonus')
        batch_op.drop_column('payed_cert')
        batch_op.drop_column('payed_card')
        batch_op.drop_column('payed_cash')
        batch_op.drop_column('payed_sum')

    with op.batch_alter_table('transaction_products', schema=None) as batch_op:
        batch_op.drop_column('barcode')
        batch_op.drop_column('weight_flag')
        batch_op.drop_column('tax_sum')
        batch_op.drop_column('print')
        batch_op.drop_column('bonus')
        batch_op.drop_column('discount')

    # ### end Alembic commands ###
